// <auto-generated />
namespace Contacts_KT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class t2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t2));
        
        string IMigrationMetadata.Id
        {
            get { return "201911220104070_t2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
